grafana:
  sidecar:
    dashboards:
      enabled: true
      additionalDashboardLabels: {}
      additionalDashboardAnnotations: {}
      label: grafana_dashboard
      labelValue: "allowed"
      folderAnnotation: dashboards-folder-name
      folder: /tmp/dashboards/
      
      provider:
        foldersFromFilesStructure: true
        allowUiUpdates: true

additionalVictoriaMetricsMap:
 custom:
  groups:
  - name: BI
    rules:
      - alert: AirflowCPUUsage
        expr: 100 - (avg(rate(node_cpu_seconds_total{project="bi",env="airflow", mode="idle"}[1m]) * 100)) > 70
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage in Airflow"
          description: "CPU usage in Airflow is above the threshold"

      - alert: AirflowMemoryUsageTypes
        expr: node_memory_MemFree_bytes{project="bi",env="airflow"} < 2e+10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low Memory Free in Airflow"
          description: "Memory free in Airflow is below the threshold"

      - alert: MetabasePublicCPUUsage
        expr: 100 - (avg(rate(node_cpu_seconds_total{job="metabase-node",instance="206.188.196.216:9100", mode="idle"}[1m]) * 100)) > 70
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage in Metabase Public"
          description: "CPU usage in Metabase Public is above the threshold"

      - alert: MetabasePrivateCPUUsage
        expr: 100 - (avg(rate(node_cpu_seconds_total{job="metabase-node",instance="192.153.57.62:9100", mode="idle"}[1m]) * 100)) > 70
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage in Metabase Private"
          description: "CPU usage in Metabase Private is above the threshold"

      - alert: DHWCPUUsage
        expr: 100 - (avg(rate(node_cpu_seconds_total{job="datawarehouse",instance="185.149.133.194:9100" , mode="idle"}[1m]) * 100)) > 70
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage in DWH"
          description: "CPU usage in DWH is above the threshold"

      - alert: DWHMemoryUsage
        expr: node_memory_MemFree_bytes{job="datawarehouse", instance="185.149.133.194:9100"} < 5e+08
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low Memory Free in DWH"
          description: "Memory free in DWH is below the threshold"

  - name: GLOBAL
    rules:
      - alert: CherryServersBalance
        expr: cherry_balance_credit < 20
        for: 5m
        labels:
          severity: critical
          target: devops
          type: billing
        annotations:
          summary: "Low CherryServers Balance"
          description: "CherryServers balance is below the threshold"

      - alert: BitLaunchBalance
        expr: bitlaunch_balance < 20
        for: 5m
        labels:
          severity: critical
          target: devops
          type: billing
        annotations:
          summary: "Low BitLaunch Balance"
          description: "BitLaunch balance is below the threshold"


  - name: CRM
    rules:
      - alert: OPENSEARCH-A_CPU_Usage
        expr: 100 - (avg(rate(node_cpu_seconds_total{job="crm-prod-opensearch-nodes", instance="209.38.251.193:9100", mode="idle"}[1m])) * 100) > 70
        for: 5m
        labels:
          severity: critical
          env: prod
          project: crm
          target: devops

      - alert: OPENSEARCH-B_CPU_Usage
        expr: 100 - (avg(rate(node_cpu_seconds_total{job="crm-prod-opensearch-nodes", instance="209.38.251.191:9100", mode="idle"}[1m])) * 100) > 70
        for: 5m
        labels:
          severity: critical
          env: prod
          project: crm
          target: devops

      - alert: OPENSEARCH-C_CPU_Usage
        expr: 100 - (avg(rate(node_cpu_seconds_total{job="crm-prod-opensearch-nodes", instance="209.38.251.198:9100", mode="idle"}[1m])) * 100) > 70
        for: 5m
        labels:
          severity: critical
          env: prod
          project: crm
          target: devops

      - alert: PGSQL_MAIN_CPU_Usage
        expr: 100 - (avg(irate(node_cpu_seconds_total{job="crm-prod-pgsql", instance="104.248.194.173:9100", mode="idle"}[1m])) * 100) > 70
        for: 5m
        labels:
          severity: critical
          env: prod
          product: pgsql-main
          project: crm
          target: devops

      - alert: PGSQL_ARCHSQL_CPU_Usage
        expr: 100 - (avg(irate(node_cpu_seconds_total{job="crm-prod-pgsql", instance="161.35.219.246:9100", mode="idle"}[1m])) * 100) > 70
        for: 5m
        labels:
          severity: critical
          env: prod
          product: pgsql-archsql
          project: crm
          target: devops

      - alert: PROD_Services_Availability
        expr: kube_deployment_status_replicas_available{namespace="platform", env="prod01"} / kube_deployment_spec_replicas{namespace="platform", env="prod01"} < 0.2
        for: 5m
        labels:
          severity: critical
          env: prod
          product: application
          project: crm
          target: devops

      - alert: CRM_PLATFORM_Pod_Restarts
        expr: sum(increase(kube_pod_container_status_restarts_total{env="prod01", namespace="platform", container=~"(accountview|affiliate|affiliate-api|analytics-api|analytics2|attachments|audit|auth2|backoffice-graphql|backoffice-graphql-ws|brand-config-service|brand-remover|callback|click-to-call|client-portal-graphql|clients-distributor|coingecko-provider|didlogic-api|email|etf-provider|external-api|hierarchy|hierarchy-updater|lead|lead-updater|liquidity-provider-adapter|localization|maintenance|matching-engine|mt-connector|mt4-alias|mt4-connector-adapter|mt4-favorite|mt4-provider|mt4-static|mt4-streaming|mt5-connector-adapter|mt5-provider|mt5-streaming|note|notification|notification-gateway|opensea-provider|operator|operator-config|payment|payment-view|profile|profileview|referral|rules-profile|scheduler|spring-boot-admin|status-alert|status-client|support-portal-graphql|swagger|trading-account|trading-activity|trading-gateway|we-trading|we-trading-chart|we-trading-provider|we-trading-streaming|wet-streaming)"}[1h])) by (container) > 1
        for: 5m
        labels:
          severity: critical
          env: prod01
          product: application
          project: crm
          target: devops

      - alert: Kafka_Lag_hierarchy_user_updated_events
        expr: sum(kafka_consumer_fetch_manager_records_lag{project="crm", env="prod01", namespace="platform", topic="hierarchy_user_updated_events"}) > 10000
        for: 5m
        labels:
          severity: critical
          env: prod01
          product: kafka-lag
          project: crm
          target: devops
      
      - alert: Kafka_Lag_profile_events
        expr: sum(kafka_consumer_fetch_manager_records_lag{project="crm", env="prod01", namespace="platform", topic="profile_events"}) > 1000
        for: 5m
        labels:
          env: prod01
          product: kafka-lag
          project: crm
          target: devops

      - alert: CRM_PROD_Apps_RPS_Lost
        expr: avg_over_time(sum by (application) (rate(http_server_requests_seconds_count{uri!~".*actuator.*|.*prometheus*|/health|/info|root", application!="matching-engine",env="prod"}[15s]))[10s:3s]) < 1e-5
        for: 5m
        labels:
          env: prod
          product: application
          project: crm
          target: devops

      - alert: CRM_PROD_Apps_PGSQL_Connection_Timeouts
        expr: rate(sum by (application) (hikaricp_connections_timeout_total{env="prod01"})[1m]) < 0
        for: 5m
        labels:
          env: prod
          product: application
          project: crm
          target: devops

      - alert: brazil_storm2_CPU_Usage
        expr: 100 - (avg(rate(node_cpu_seconds_total{job="backoffice-proxy-nodes", instance="default-crm.me:443", mode="idle"}[1m])) * 100) > 70
        for: 5m
        labels:
          severity: warning
          env: prod
          product: backoffice-proxy
          project: crm
          target: devops
        annotations:
          description: '[brazil] storm2 - CPU Usage alert'
          summary: '[brazil] storm2 - CPU Usage is above the threshold'

      - alert: brazil_storm1_CPU_Usage
        expr: 100 - (avg(rate(node_cpu_seconds_total{job="backoffice-proxy-nodes", instance="trendsales.cc:443", mode="idle"}[1m])) * 100) > 70
        for: 5m
        labels:
          severity: warning
          env: prod
          product: backoffice-proxy
          project: crm
          target: devops
        annotations:
          description: '[brazil] storm1 - CPU Usage alert'
          summary: '[brazil] storm1 - CPU Usage is above the threshold'

      - alert: brazil_storm3_CPU_Usage
        expr: 100 - (avg(rate(node_cpu_seconds_total{job="backoffice-proxy-nodes", instance="default-crm.cc:443", mode="idle"}[1m])) * 100) > 70
        for: 5m
        labels:
          severity: warning
          env: prod
          product: backoffice-proxy
          project: crm
          target: devops
        annotations:
          description: '[brazil] storm3 - CPU Usage alert'
          summary: '[brazil] storm3 - CPU Usage is above the threshold'

#      - alert: '[brazil] storm1 Network Lost'
#        expr: rate(node_network_transmit_bytes_total{job="backoffice-proxy-nodes", instance="trendsales.cc:443", device=~"eth0|ens18|eno1"}[$__rate_interval]) * 8 < 1000
#        for: 5m
#        labels:
#          env: prod
#          product: backoffice-proxy
#          project: crm
#          target: devops
#        annotations:
#          dashboardUid: gtB7_sL4k
#          panelId: "8"
#
#      - alert: '[brazil] storm2 Network Lost'
#        expr: rate(node_network_transmit_bytes_total{job="backoffice-proxy-nodes", instance="default-crm.me:443", device=~"eth0|ens18|eno1"}[$__rate_interval]) * 8 < 1000
#        for: 5m
#        labels:
#          env: prod
#          product: backoffice-proxy
#          project: crm
#          target: devops
#        annotations:
#          dashboardUid: gtB7_sL4k
#          panelId: "8"
#          
#      - alert: '[brazil] storm3 Network Lost'
#        expr: rate(node_network_transmit_bytes_total{job="backoffice-proxy-nodes", instance="default-crm.cc:443", device=~"eth0|ens18|eno1"}[$__rate_interval]) * 8 < 1000
#        for: 5m
#        labels:
#          env: prod
#          product: backoffice-proxy
#          project: crm
#          target: devops
#        annotations:
#          dashboardUid: gtB7_sL4k
#         panelId: "8"

  - name: CRYPTOPAY
    rules:
    - alert: Balances_mismatch
      expr: explorer_processed_balances_total{cluster_name="crypto-dev01", network="eth"} - explorer_processed_wallets_total{cluster_name="crypto-dev01", network="eth"} * explorer_supported_currencies_total{cluster_name="crypto-dev01", network="eth"} > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        description: Balances mismatch alert
        summary: Balances mismatch detected in crypto-dev01

    - alert: BTC_Failed_Transactions
      expr: core_transactions_states_total{cluster_name="crypto-prod01", currency="BTC", state="failed"} > 1
      for: 10s
      labels:
        target: crp_devs
      annotations:
        description: Number of failed BTC transactions more than 10
        summary: BTC Failed Transactions exceed threshold



