{{- range $path, $data := .Files.Glob "rules/**.yaml" }}
{{- $dirsList := $path | splitList "/" }}
{{- $rootDir := index $dirsList 1 }} {{/* get root dirs names under dashboards dir */}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Values.namespace }}
  name: grafana-alert-{{ base $path }}
  labels:
    {{- include "grafana-alerts.labels" $ | nindent 4 }}
    # this labes is used to discover configmap by grafana sidecar
data:
  {{ base $path }}: |-
    {{- $data | toString | nindent 4 }}
{{ end }}
