{
 "title": "Bitcoin Node",
 "description": "Monitor your Bitcoin core node and aspects of the network.",
 "tags": [ "bitcoin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "project",
    "query": {
     "query": "label_values(kubernetes_build_info,project)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info{project=\"$project\"}, env)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Block Creation Rate",
   "type": "graph",
   "description": "Number of blocks created per day using different trailing rates.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(sum(rate(bitcoin_blocks{env=\"$cluster\"}[3h])) * 3600 * 24)",
     "legendFormat": "3h"
    },
    {
     "expr": "floor(sum(rate(bitcoin_blocks{env=\"$cluster\"}[6h])) * 3600 * 24)",
     "legendFormat": "6h"
    },
    {
     "expr": "floor(sum(rate(bitcoin_blocks{env=\"$cluster\"}[12h])) * 3600 * 24)",
     "legendFormat": "12h"
    },
    {
     "expr": "floor(sum(rate(bitcoin_blocks{env=\"$cluster\"}[7d])) * 3600 * 24)",
     "legendFormat": "7d"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "graph",
   "description": "Difficulty value",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(bitcoin_difficulty{env=\"$cluster\"})",
     "legendFormat": "difficulty"
    }
   ]
  },
  {
   "title": "Network Hash Rate",
   "type": "graph",
   "description": "Estimated network hashes per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(bitcoin_hashps{env=\"$cluster\"})",
     "legendFormat": "120-blocks"
    },
    {
     "expr": "avg(bitcoin_hashps_neg1{env=\"$cluster\"})",
     "legendFormat": "last-difficulty"
    }
   ]
  },
  {
   "title": "Block value",
   "type": "graph",
   "description": "Value of the block transactions in BTC.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bitcoin_latest_block_value{env=\"$cluster\"})",
     "legendFormat": "BTC"
    }
   ]
  },
  {
   "title": "Chain Branches",
   "type": "graph",
   "description": "Number of tips seen in the chain.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(bitcoin_num_chaintips{env=\"$cluster\"})",
     "legendFormat": "tips"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "description": "Sent and received traffic rates",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bitcoin_total_bytes_sent{env=\"$cluster\"}[5m]))",
     "legendFormat": "sent"
    },
    {
     "expr": "-sum(irate(bitcoin_total_bytes_recv{env=\"$cluster\"}[10m]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Estimated Fee",
   "type": "graph",
   "description": "The estimated smart fee for confirmation of transactions in a given number of blocks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(bitcoin_est_smart_fee_2{env=\"$cluster\"})",
     "legendFormat": "2-blocks"
    },
    {
     "expr": "avg(bitcoin_est_smart_fee_20{env=\"$cluster\"})",
     "legendFormat": "20-blocks"
    },
    {
     "expr": "avg(bitcoin_est_smart_fee_3{env=\"$cluster\"})",
     "legendFormat": "3-blocks"
    },
    {
     "expr": "avg(bitcoin_est_smart_fee_5{env=\"$cluster\"})",
     "legendFormat": "5-blocks"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "graph",
   "description": "The Bitcoin protocol and server versions.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "protocol version" }
   ],
   "targets": [
    {
     "expr": "avg(bitcoin_protocol_version{env=\"$cluster\"})",
     "legendFormat": "protocol"
    },
    {
     "expr": "avg(bitcoin_server_version{env=\"$cluster\"})",
     "legendFormat": "server"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "description": "Number of peers that have been banned and the reason for the ban.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(bitcoin_banned_until{env=\"$cluster\"}) by (reason)",
     "legendFormat": "ban - {{ reason }}"
    },
    {
     "expr": "sum(bitcoin_peers{env=\"$cluster\"})",
     "legendFormat": "peers"
    }
   ]
  }
 ]
}