{
 "title": "Blockchain Hight Block",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "project",
    "query": {
     "query": "label_values(kubernetes_build_info,project)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info{project=\"$project\"}, env)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Tron",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tron",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (managed_exporter_tron_blockHeight{env=\"$cluster\",provider=~\".+\", location=\"external\"}) by (provider)",
     "legendFormat": "{{ provider }}"
    },
    {
     "expr": "sum (managed_exporter_tron_blockHeight{env=\"$cluster\",provider=~\".+\", location=\"internal\"}) by (provider)",
     "legendFormat": "node: {{ provider }}"
    }
   ]
  },
  {
   "title": "Tron Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(managed_exporter_tron_blockHeight{env=\"$cluster\",provider=~\"trongrid\"}) by(provider) - on() group_right() managed_exporter_tron_blockHeight{env=\"$cluster\",location=\"internal\"}",
     "legendFormat": "Compare trongrid with  {{ provider }}"
    }
   ]
  },
  {
   "title": "Bitcoin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bitcoin",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "managed_exporter_bitcoin_blockHeight{env=\"$cluster\",provider=~\".+\"}",
     "legendFormat": "{{ provider }}"
    },
    {
     "expr": "sum (bitcoin_blocks{env=\"$cluster\"}) by (instance)",
     "legendFormat": "node: {{ instance }}"
    }
   ]
  },
  {
   "title": "Bitcoin Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(managed_exporter_bitcoin_blockHeight{env=\"$cluster\", provider=~\"blockchain_info\"}) by(provider) - on() group_right() sum(bitcoin_blocks{env=\"$cluster\"}) by (instance)",
     "legendFormat": "Compare blockchain_info with  {{ instance }}"
    },
    {
     "expr": "sum(managed_exporter_bitcoin_blockHeight{env=\"$cluster\", provider=~\"blockcypher\"}) by(provider) - on() group_right() sum(bitcoin_blocks{env=\"$cluster\"}) by (instance)",
     "legendFormat": "Compare blockcypher with  {{ instance }}"
    }
   ]
  },
  {
   "title": "Ethereum",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ethereum",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "managed_exporter_ethereum_blockHeight{env=\"$cluster\",provider=~\"in.*|etherscan\"}",
     "legendFormat": "{{provider}}"
    },
    {
     "expr": "sum (geth_block{env=\"$cluster\"}) by (instance)",
     "legendFormat": "node: {{ instance }}"
    }
   ]
  },
  {
   "title": "Ethereum Latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(managed_exporter_ethereum_blockHeight{env=\"$cluster\",provider=~\"etherscan\"}) by(provider) - on() group_right() geth_block{env=\"$cluster\"}",
     "legendFormat": "Compare etherscan with  {{ instance }}"
    },
    {
     "expr": "sum(managed_exporter_ethereum_blockHeight{env=\"$cluster\",provider=~\"infura\"}) by(provider) - on() group_right() geth_block{env=\"$cluster\"}",
     "legendFormat": "Compare infura with  {{ instance }}"
    }
   ]
  }
 ]
}