{
 "title": "Blockhain Explorers",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster_name)" } },
   { "name": "network", "query": { "query": "label_values(network)\n" } }
  ]
 },
 "panels": [
  {
   "title": "Last processed block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "explorer_last_processed_block{network=\"$network\", cluster_name=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Currencies total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "explorer_supported_currencies_total{network=\"$network\", cluster_name=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(gin_request_duration_bucket{cluster_name=\"$cluster\", service=\"$network-explorer-api\"}[5m])) by (le, instance))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(gin_request_duration_bucket{cluster_name=\"$cluster\", service=\"$network-explorer-api\"}[5m])) by (le, instance))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum (gin_request_duration_sum{cluster_name=\"$cluster\",service=\"$network-explorer-api\"}) / sum(gin_request_duration_count{cluster_name=\"$cluster\",service=\"$network-explorer-api\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Transactions total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "explorer_processed_transactions_total{cluster_name=\"$cluster\", network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
   "targets": [
    {
     "expr": "explorer_processed_blocks_total{cluster_name=\"$cluster\", network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wallets total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "explorer_processed_wallets_total{cluster_name=\"$cluster\", network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Balances total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "explorer_processed_balances_total{cluster_name=\"$cluster\", network=\"$network\"}",
     "legendFormat": "actual"
    },
    {
     "expr": "explorer_processed_wallets_total{cluster_name=\"$cluster\", network=\"$network\"}*explorer_supported_currencies_total{cluster_name=\"$cluster\", network=\"$network\"}+1",
     "legendFormat": "threshold"
    }
   ]
  },
  {
   "title": "URI Request",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(uri) (gin_uri_request_total{cluster_name=\"$cluster\",service=\"$network-explorer-api\",uri!=\"\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Method",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(method) (gin_uri_request_total{cluster_name=\"$cluster\",service=\"$network-explorer-api\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(code) (gin_uri_request_total{cluster_name=\"$cluster\",service=\"$network-explorer-api\"})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Traffic In-Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(gin_request_body_total{cluster_name=\"$cluster\", service=\"$network-explorer-api\"}[5m])",
     "legendFormat": "{{instance}}-in"
    },
    {
     "expr": "rate(gin_response_body_total{cluster_name=\"$cluster\", service=\"$network-explorer-api\"}[5m])",
     "legendFormat": "{{instance}}-out"
    }
   ]
  },
  {
   "title": "Balances mismatch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "explorer_processed_balances_total{cluster_name=\"$cluster\", network=\"$network\"} - explorer_processed_wallets_total{cluster_name=\"$cluster\", network=\"$network\"}*explorer_supported_currencies_total{cluster_name=\"$cluster\", network=\"$network\"}",
     "legendFormat": "mismatch"
    }
   ]
  }
 ]
}