{
 "title": "Bussines Core",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Total failed transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(core_transactions_states_total{cluster_name=\"$cluster\", state=\"failed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total completed transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(core_transactions_states_total{cluster_name=\"$cluster\", state=\"completed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(gin_request_duration_bucket{cluster_name=\"$cluster\", service=\"crypto-core\"}[5m])) by (le, instance))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(gin_request_duration_bucket{cluster_name=\"$cluster\", service=\"crypto-core\"}[5m])) by (le, instance))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum (gin_request_duration_sum{cluster_name=\"$cluster\", service=\"crypto-core\"}) / sum(gin_request_duration_count{cluster_name=\"$cluster\",service=\"crypto-core\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Total users",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_users_total{cluster_name=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total brands",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_brands_total{cluster_name=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total wallets",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_wallets_total{cluster_name=\"$cluster\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "URI Request",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(uri) (gin_uri_request_total{cluster_name=\"$cluster\", service=\"crypto-core\", uri!=\"\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Method",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (gin_uri_request_total{cluster_name=\"$cluster\", service=\"crypto-core\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code) (gin_uri_request_total{cluster_name=\"$cluster\", service=\"crypto-core\"})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Internal errors rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum by(code) (gin_uri_request_total{cluster_name=\"$cluster\", service=\"crypto-core\", code=\"500\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic In-Out",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(gin_request_body_total{cluster_name=\"$cluster\", service=\"crypto-core\"}[5m])",
     "legendFormat": "{{instance}}-in"
    },
    {
     "expr": "rate(gin_response_body_total{cluster_name=\"$cluster\", service=\"crypto-core\"}[5m])",
     "legendFormat": "{{instance}}-out"
    }
   ]
  },
  { "title": "Transactions details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "BTC Total Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_types_total{cluster_name=\"$cluster\", currency=\"BTC\", type=\"total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BTC Transactions Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_types_total{cluster_name=\"$cluster\", currency=\"BTC\", type!=\"total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BTC Transactions States",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_states_total{cluster_name=\"$cluster\", currency=\"BTC\", state !='failed'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BTC Failed Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 40 },
   "targets": [
    {
     "expr": "core_transactions_states_total{cluster_name=\"$cluster\", currency=\"BTC\", state=\"failed\"}",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "BTC Failed Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_states_total{cluster_name=\"$cluster\", currency=\"BTC\", state=\"failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USDT Total Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_types_total{cluster_name=\"$cluster\", currency=\"USDT\", type=\"total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USDT Transactions Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_types_total{cluster_name=\"$cluster\", currency=\"USDT_ERC20\", type!=\"total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USDT Transactions States",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_states_total{cluster_name=\"$cluster\", currency=\"USDT\", state!=\"failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USDT Failed Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 48 },
   "targets": [
    {
     "expr": "core_transactions_states_total{cluster_name=\"$cluster\", currency=\"USDT\", state=\"failed\"}",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "USDT Failed Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_states_total{cluster_name=\"$cluster\", currency=\"USDT\", state=\"failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETH Total Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_types_total{cluster_name=\"$cluster\", currency=\"ETH\", type=\"total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETH Transactions Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_types_total{cluster_name=\"$cluster\", currency=\"ETH\", type!=\"total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETH Transactions States",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_states_total{cluster_name=\"$cluster\", currency=\"ETH\", state!=\"failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETH Failed Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 56 },
   "targets": [
    {
     "expr": "core_transactions_states_total{cluster_name=\"$cluster\", currency=\"ETH\", state=\"failed\"}",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "ETH Failed Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_states_total{cluster_name=\"$cluster\", currency=\"ETH\", state=\"failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USDT_ERC20 Total Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_types_total{cluster_name=\"$cluster\", currency=\"USDT_ERC20\", type=\"total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USDT_ERC20 Transactions Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_types_total{cluster_name=\"$cluster\", currency=\"USDT_ERC20\", type!=\"total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USDT_ERC20 Transactions States",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_states_total{cluster_name=\"$cluster\", currency=\"USDT_ERC20\", state!=\"failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USDT_ERC20 Failed Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 64 },
   "targets": [
    {
     "expr": "core_transactions_states_total{cluster_name=\"$cluster\", currency=\"USDT_ERC20\", state=\"failed\"}",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "USDT_ERC20 Failed Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_states_total{cluster_name=\"$cluster\", currency=\"USDT_ERC20\", state=\"failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USDC Total Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_types_total{cluster_name=\"$cluster\", currency=\"USDC\", type=\"total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USDC Transactions Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_types_total{cluster_name=\"$cluster\", currency=\"USDC\", type!=\"total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USDC Transactions States",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_states_total{cluster_name=\"$cluster\", currency=\"USDC\", state!=\"failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USDC Failed Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 72 },
   "targets": [
    {
     "expr": "core_transactions_states_total{cluster_name=\"$cluster\", currency=\"USDC\", state=\"failed\"}",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "USDC Failed Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_states_total{cluster_name=\"$cluster\", currency=\"USDC\", state=\"failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAI Total Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_types_total{cluster_name=\"$cluster\", currency=\"DAI\", type=\"total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAI Transactions Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_types_total{cluster_name=\"$cluster\", currency=\"DAI\", type!=\"total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAI Transactions States",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_states_total{cluster_name=\"$cluster\", currency=\"DAI\", state!=\"failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAI Failed Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 80 },
   "targets": [
    {
     "expr": "core_transactions_states_total{cluster_name=\"$cluster\", currency=\"DAI\", state=\"failed\"}",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "DAI Failed Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_transactions_states_total{cluster_name=\"$cluster\", currency=\"DAI\", state=\"failed\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}