{
 "title": "YACE AWS RDS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "query": {
     "query": "label_values(kubernetes_build_info,project)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info{project=\"$project\"}, env)"
    }
   },
   { "name": "db", "label": "db", "query": { "query": "aws_rds_cpuutilization_average" } }
  ]
 },
 "panels": [
  {
   "title": "CPUUtilizationAverage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(aws_rds_cpuutilization_average{env=\"$cluster\", dimension_DBInstanceIdentifier=\"$db\"}) by (dimension_DBInstanceIdentifier)",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "EBSIOBalanceAverage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(aws_rds_ebsiobalance_percent_average{env=\"$cluster\",dimension_DBInstanceIdentifier=\"$db\"}) by (dimension_DBInstanceIdentifier)",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "DatabaseConnectionsAverage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aws_rds_database_connections_average{env=\"$cluster\", dimension_DBInstanceIdentifier=\"$db\"}) by (dimension_DBInstanceIdentifier)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FreeStorageSpaceAverage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(aws_rds_free_storage_space_average{env=\"$cluster\", dimension_DBInstanceIdentifier=\"$db\"}  / 1000000) by (dimension_DBInstanceIdentifier)",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "FreeableMemoryAverage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(aws_rds_freeable_memory_average{env=\"$cluster\",dimension_DBInstanceIdentifier=\"$db\"} / 1000000) by (dimension_DBInstanceIdentifier)",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "ReadIOPSAverage/WriteIOPSAvarage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(aws_rds_read_iops_average{env=\"$cluster\",dimension_DBInstanceIdentifier=\"$db\"}) by (dimension_DBInstanceIdentifier)",
     "legendFormat": "aws_rds_read_iops_average - {{dimension_DBInstanceIdentifier}}"
    },
    {
     "expr": "sum(aws_rds_write_iops_average{dimension_DBInstanceIdentifier=\"$db\"}) by (dimension_DBInstanceIdentifier)",
     "legendFormat": "aws_rds_write_iops_average - {{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "ReadLatencyAverage/WriteLatencyAvarage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(aws_rds_read_latency_average{dimension_DBInstanceIdentifier=\"$db\"} * 1000) by (dimension_DBInstanceIdentifier)",
     "legendFormat": "aws_rds_read_latency_average - {{dimension_DBInstanceIdentifier}}"
    },
    {
     "expr": "sum(aws_rds_write_latency_average{dimension_DBInstanceIdentifier=\"$db\"} * 1000) by (dimension_DBInstanceIdentifier)",
     "legendFormat": "aws_rds_write_latency_average - {{dimension_DBInstanceIdentifier}}"
    }
   ]
  }
 ]
}