{
 "title": "AirflowNode",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Current CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{project=\"bi\",env=\"airflow\", mode=\"idle\"}[1m]) * 100))\n"
    }
   ]
  },
  {
   "title": "Current Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{project=\"bi\",env=\"airflow\"}) /\n  avg(node_memory_MemTotal_bytes{project=\"bi\",env=\"airflow\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{project=\"bi\",env=\"airflow\", mode=\"idle\"}[1m]) * 100))\n",
     "legendFormat": "CPU Avg"
    }
   ]
  },
  {
   "title": "Memory Usage Types",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{project=\"bi\",env=\"airflow\"}\n-\n  node_memory_MemFree_bytes{project=\"bi\",env=\"airflow\"}\n-\n  node_memory_Buffers_bytes{project=\"bi\",env=\"airflow\"}\n-\n  node_memory_Cached_bytes{project=\"bi\",env=\"airflow\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"airflow\", instance=\"airflow-node.cyberhat.guru:443\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"airflow\", instance=\"airflow-node.cyberhat.guru:443\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"airflow\", instance=\"airflow-node.cyberhat.guru:443\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{project=\"bi\",env=\"airflow\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{project=\"bi\",env=\"airflow\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{project=\"bi\",env=\"airflow\"}",
     "legendFormat": "15m"
    },
    {
     "expr": "count(node_cpu_seconds_total{project=\"bi\",env=\"airflow\", mode=\"idle\"})",
     "legendFormat": "Cores"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pods Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{project=\"bi\", env=\"airflow\", namespace=\"airflow\"}) - 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "table",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node_filesystem_size_bytes{project=\"bi\",env=\"airflow\", fstype!=\"\", mountpoint=~\"/opt/data|/\"})\n"
    },
    {
     "expr": "max by (mountpoint) (node_filesystem_avail_bytes{project=\"bi\",env=\"airflow\", fstype!=\"\", mountpoint=~\"/opt/data|/\"})\n"
    }
   ]
  },
  {
   "title": "ROOT Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{project=\"bi\",env=\"airflow\", device=~\"(/dev/)?(dm-0)\"}[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{project=\"bi\",env=\"airflow\", device=~\"(/dev/)?(dm-0)\"}[$__rate_interval])",
     "legendFormat": "write"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{project=\"bi\",env=\"airflow\", device=~\"(/dev/)?(dm-0)\"}[$__rate_interval])",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "RAID Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{project=\"bi\",env=\"airflow\", device=~\"(/dev/)?(md4)\"}[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{project=\"bi\",env=\"airflow\", device=~\"(/dev/)?(md4)\"}[$__rate_interval])",
     "legendFormat": "write"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{project=\"bi\",env=\"airflow\", device=~\"(/dev/)?(md4)\"}[$__rate_interval])",
     "legendFormat": "io time"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Internet Network",
   "type": "timeseries",
   "description": "Network (bits/s)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(node_network_receive_bytes_total{project=\"bi\",env=\"airflow\", device=\"ens1f0\"}[$__rate_interval]) * 8) * -1",
     "legendFormat": "in"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{project=\"bi\",env=\"airflow\", device=\"ens1f0\"}[$__rate_interval]) * 8",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "COM Network",
   "type": "timeseries",
   "description": "Network (bits/s)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(node_network_receive_bytes_total{project=\"bi\",env=\"airflow\", device=\"bond0\"}[$__rate_interval]) * 8) * -1",
     "legendFormat": "in"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{project=\"bi\",env=\"airflow\", device=\"bond0\"}[$__rate_interval]) * 8",
     "legendFormat": "out"
    }
   ]
  }
 ]
}