{
 "title": "DataWarehouse",
 "tags": [
  "datawarehouse",
  "node"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "PGSQL Started",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_postmaster_start_time_seconds{instance=\"185.149.133.194:9187\", job=\"datawarehouse\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{job=\"datawarehouse\",instance=\"185.149.133.194:9100\", mode=\"idle\"}[1m]) * 100))\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"datawarehouse\", instance=\"185.149.133.194:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"datawarehouse\", instance=\"185.149.133.194:9100\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{job=\"datawarehouse\",instance=\"185.149.133.194:9100\", mode=\"idle\"}[1m]) * 100))\n",
     "legendFormat": "CPU Avg"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"datawarehouse\", instance=\"185.149.133.194:9100\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=\"datawarehouse\", instance=\"185.149.133.194:9100\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=\"datawarehouse\", instance=\"185.149.133.194:9100\"}",
     "legendFormat": "15m"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"datawarehouse\", instance=\"185.149.133.194:9100\", mode=\"idle\"})",
     "legendFormat": "Cores"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node_filesystem_size_bytes{job=\"datawarehouse\", instance=\"185.149.133.194:9100\", fstype!=\"\", mountpoint=~\"/|/opt/data\"})\n"
    },
    {
     "expr": "max by (mountpoint) (node_filesystem_avail_bytes{job=\"datawarehouse\", instance=\"185.149.133.194:9100\", fstype!=\"\", mountpoint=~\"/|/opt/data\"})\n"
    }
   ]
  },
  {
   "title": "Memory Usage Types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"datawarehouse\", instance=\"185.149.133.194:9100\"}\n-\n  node_memory_MemFree_bytes{job=\"datawarehouse\", instance=\"185.149.133.194:9100\"}\n-\n  node_memory_Buffers_bytes{job=\"datawarehouse\", instance=\"185.149.133.194:9100\"}\n-\n  node_memory_Cached_bytes{job=\"datawarehouse\", instance=\"185.149.133.194:9100\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"datawarehouse\", instance=\"185.149.133.194:9100\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"datawarehouse\", instance=\"185.149.133.194:9100\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"datawarehouse\", instance=\"185.149.133.194:9100\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"datawarehouse\", instance=\"185.149.133.194:9100\", device=~\"(/dev/)?(md10)\"}[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"datawarehouse\", instance=\"185.149.133.194:9100\", device=~\"(/dev/)?(md10)\"}[$__rate_interval])",
     "legendFormat": "write"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"datawarehouse\", instance=\"185.149.133.194:9100\", device=~\"(/dev/)?(md10)\"}[$__rate_interval])",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "description": "Network (bits/s)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(node_network_receive_bytes_total{job=\"datawarehouse\", instance=\"185.149.133.194:9100\", device=\"enp175s0f0\"}[$__rate_interval]) * 8) * -1",
     "legendFormat": "in"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"datawarehouse\", instance=\"185.149.133.194:9100\", device=\"enp175s0f0\"}[$__rate_interval]) * 8",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Longest Transaction",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration{ instance=\"185.149.133.194:9187\", usename!~\"(data_sync|divanov|aleleko|postgres|)\", datname!=\"postgres\" } > 0",
     "legendFormat": "{{ datname }} - {{usename}} - [{{ state }}]"
    }
   ]
  }
 ]
}