---
repositories:
- name: victoria-metrics
  url: https://victoriametrics.github.io/helm-charts/


releases:
  
- name: vmoper
  namespace: vm
  chart: vm/victoria-metrics-k8s-stack
  values:
    - ../config/helmfile-config.yaml
  hooks:
      - events: ["prepare"]
        showlogs: true
        command: "apply"
        args:
          - "delete"
          - "-f"
          - "https://raw.githubusercontent.com/VictoriaMetrics/helm-charts/master/charts/victoria-metrics-k8s-stack/crds/crd.yaml"

- name: gf-dash
  namespace: vm
  chart: ../charts/grafana-dashboards
  needs:
   - vmoper

#- name: alerts
#  namespace: vm
#  chart: ../charts/alerts
#  needs:
#   - vmoper