{
 "title": "BackOffice Proxy Nodes",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"backoffice-proxy-nodes\"}, instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"backoffice-proxy-nodes\",instance=\"$instance\", mode=\"idle\"}[1m]) * 100))\n",
     "legendFormat": "cpu avg"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"backoffice-proxy-nodes\", instance=\"$instance\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"backoffice-proxy-nodes\", instance=\"$instance\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"backoffice-proxy-nodes\",instance=\"$instance\", mode=\"idle\"}[1m]) * 100))\n",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"backoffice-proxy-nodes\", instance=\"$instance\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"backoffice-proxy-nodes\", instance=\"$instance\"})\n* 100\n)\n",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"backoffice-proxy-nodes\", instance=\"$instance\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=\"backoffice-proxy-nodes\", instance=\"$instance\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=\"backoffice-proxy-nodes\", instance=\"$instance\"}",
     "legendFormat": "15m"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"backoffice-proxy-nodes\", instance=\"$instance\", mode=\"idle\"})",
     "legendFormat": "cores"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"backoffice-proxy-nodes\", instance=\"$instance\", device=~\"eth0|ens18|eno1\"}[$__rate_interval]) * 8",
     "legendFormat": "Out"
    },
    {
     "expr": "(rate(node_network_receive_bytes_total{job=\"backoffice-proxy-nodes\", instance=\"$instance\", device=~\"eth0|ens18|eno1\"}[$__rate_interval]) * 8) * -1",
     "legendFormat": "In"
    }
   ]
  }
 ]
}