{
 "title": "General Services Statistics",
 "tags": [ "stack" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   { "name": "project", "label": "project", "query": "crm" },
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(system_cpu_usage{project=\"$project\"},env)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(application) (system_cpu_usage{project=\"$project\",env=\"$env\"})",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(application) (system_cpu_usage{project=\"$project\",env=\"$env\"})",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{project=\"$project\",env=\"$env\"}",
     "legendFormat": "{{application}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(application, instance) (jvm_memory_used_bytes{area=\"heap\", project=\"$project\",env=\"$env\"})",
     "legendFormat": "{{application}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "RPS (peak oriented)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time(sum by (application) (irate( http_server_requests_seconds_count{uri!~\".*actuator.*\", uri!~\".*prometheus*\", uri!~\"/health\", uri!~\"/info\", uri!~\"root\", project=\"$project\",env=\"$env\"}[15s] ))[$__interval:3s] )",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "RPS (avg oriented)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(sum by (application) (rate(http_server_requests_seconds_count{uri!~\".*actuator.*\", uri!~\".*prometheus*\", uri!~\"/health\", uri!~\"/info\", uri!~\"root\", project=\"$project\",env=\"$env\"}[15s]))[$__interval:3s])",
     "legendFormat": "{{application}}"
    }
   ]
  }
 ]
}