{
 "title": "MSK Cluster Overview",
 "tags": [
  "kafka",
  "aws",
  "prod"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(kafka_server_KafkaServer_Value,project)"
    }
   },
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(kafka_server_KafkaServer_Value{project=\"$project\"},env)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Critical Values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{name=\"OfflinePartitionsCount\"}) without (instance)"
    }
   ]
  },
  {
   "title": "In-Sync Replica state change",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_controller_ControllerStats_Count{name=\"IsrChangeRateAndTimeMs\"}[30m])) without (instance)"
    }
   ]
  },
  {
   "title": "Log Flush Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_log_LogFlushStats_Count{name=\"LogFlushRateAndTimeMs\"}) without (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{name=\"GlobalTopicCount\"}) without (instance)"
    }
   ]
  },
  {
   "title": "Preferred Leader Imbalance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{name=\"PreferredReplicaImbalanceCount\"}) without (instance)"
    }
   ]
  },
  {
   "title": "Total Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{name=\"GlobalPartitionCount\"}) without (instance)"
    }
   ]
  },
  {
   "title": "Fetch Queue Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_Fetch_queue_size) without (instance)"
    }
   ]
  },
  {
   "title": "MessagesInPerSec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{env=\"$env\", name=\"MessagesInPerSec\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ReplicationBytesInPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{project=\"crm\",env=\"prod\",job=\"kafka\",name=\"ReplicationBytesInPerSec\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ReplicationBytesOutPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{job=\"kafka\",name=\"ReplicationBytesOutPerSec\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TotalProduceRequestsPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{job=\"kafka\",name=\"TotalProduceRequestsPerSec\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Under replicated partitions by Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_cluster_Partition_Value{job=\"kafka\",name=\"UnderReplicated\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "ZooKeeperDisconnectsPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_SessionExpireListener_OneMinuteRate{name=\"ZooKeeperDisconnectsPerSec\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesInPerSec\"}[1m])) by (name)",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesOutPerSec\"}[1m])) by (name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Network: RequestsPerSec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_RequestMetrics_OneMinuteRate{name=\"RequestsPerSec\"  }) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network: CPU Idle Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_Processor_Value{name=\"IdlePercent\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network: ErrorsPerSec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_RequestMetrics_OneMinuteRate{name=\"ErrorsPerSec\"  }) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}