{
 "title": "Opensearch Nodes",
 "tags": [
  "opensearch",
  "crm",
  "prod"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Main Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU - A",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"crm-prod-opensearch-nodes\",instance=\"209.38.251.193:9100\", mode=\"idle\"}[1m]) * 100))\n",
     "legendFormat": "cpu avg"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.193:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.193:9100\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "CPU - B",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"crm-prod-opensearch-nodes\",instance=\"209.38.251.191:9100\", mode=\"idle\"}[1m]) * 100))\n",
     "legendFormat": "cpu avg"
    }
   ]
  },
  {
   "title": "Memory - B",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "CPU - C",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"crm-prod-opensearch-nodes\",instance=\"209.38.251.198:9100\", mode=\"idle\"}[1m]) * 100))\n",
     "legendFormat": "cpu avg"
    }
   ]
  },
  {
   "title": "Memory - C",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.198:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.198:9100\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "Load Average - A",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.193:9100\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.193:9100\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.193:9100\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.193:9100\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "Load Average - B",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "Load Average - C",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "Disk Space Usage - A",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node_filesystem_size_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.193:9100\", fstype!=\"\", mountpoint=\"/\"})\n"
    },
    {
     "expr": "max by (mountpoint) (node_filesystem_avail_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.193:9100\", fstype!=\"\", mountpoint=\"/\"})\n"
    }
   ]
  },
  {
   "title": "Disk Space Usage - B",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node_filesystem_size_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\", fstype!=\"\", mountpoint=\"/\"})\n"
    },
    {
     "expr": "max by (mountpoint) (node_filesystem_avail_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\", fstype!=\"\", mountpoint=\"/\"})\n"
    }
   ]
  },
  {
   "title": "Disk Space Usage - C",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node_filesystem_size_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.198:9100\", fstype!=\"\", mountpoint=\"/\"})\n"
    },
    {
     "expr": "max by (mountpoint) (node_filesystem_avail_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.198:9100\", fstype!=\"\", mountpoint=\"/\"})\n"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Usage - A",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{job=\"crm-prod-opensearch-nodes\",instance=\"209.38.251.193:9100\", mode=\"idle\"}[1m]) * 100))\n",
     "legendFormat": "memory used"
    }
   ]
  },
  {
   "title": "CPU Usage - B",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"crm-prod-opensearch-nodes\",instance=\"209.38.251.191:9100\", mode=\"idle\"}[1m]) * 100))\n",
     "legendFormat": "memory used"
    }
   ]
  },
  {
   "title": "CPU Usage - C",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"crm-prod-opensearch-nodes\",instance=\"209.38.251.198:9100\", mode=\"idle\"}[1m]) * 100))\n",
     "legendFormat": "memory used"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage - A",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(\n  node_memory_MemTotal_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.193:9100\"}\n-\n  node_memory_MemFree_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.193:9100\"}\n-\n  node_memory_Buffers_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.193:9100\"}\n-\n  node_memory_Cached_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.193:9100\"}\n)\n",
       "legendFormat": "memory used"
      },
      {
       "expr": "node_memory_Buffers_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.193:9100\"}",
       "legendFormat": "memory buffers"
      },
      {
       "expr": "node_memory_Cached_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.193:9100\"}",
       "legendFormat": "memory cached"
      },
      {
       "expr": "node_memory_MemFree_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.193:9100\"}",
       "legendFormat": "memory free"
      }
     ]
    },
    {
     "title": "Memory Usage - B",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(\n  node_memory_MemTotal_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\"}\n-\n  node_memory_MemFree_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\"}\n-\n  node_memory_Buffers_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\"}\n-\n  node_memory_Cached_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\"}\n)\n",
       "legendFormat": "memory used"
      },
      {
       "expr": "node_memory_Buffers_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\"}",
       "legendFormat": "memory buffers"
      },
      {
       "expr": "node_memory_Cached_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\"}",
       "legendFormat": "memory cached"
      },
      {
       "expr": "node_memory_MemFree_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\"}",
       "legendFormat": "memory free"
      }
     ]
    },
    {
     "title": "Memory Usage - C",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(\n  node_memory_MemTotal_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.198:9100\"}\n-\n  node_memory_MemFree_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.198:9100\"}\n-\n  node_memory_Buffers_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.198:9100\"}\n-\n  node_memory_Cached_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.198:9100\"}\n)\n",
       "legendFormat": "memory used"
      },
      {
       "expr": "node_memory_Buffers_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.198:9100\"}",
       "legendFormat": "memory buffers"
      },
      {
       "expr": "node_memory_Cached_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.198:9100\"}",
       "legendFormat": "memory cached"
      },
      {
       "expr": "node_memory_MemFree_bytes{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.198:9100\"}",
       "legendFormat": "memory free"
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Network IO - A",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.193:9100\", device=\"eth0\"}[$__rate_interval]) * 8",
     "legendFormat": "Out"
    },
    {
     "expr": "(rate(node_network_receive_bytes_total{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.193:9100\", device=\"eth0\"}[$__rate_interval]) * 8) * -1",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Network IO - B",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\", device=\"eth0\"}[$__rate_interval]) * 8",
     "legendFormat": "Out"
    },
    {
     "expr": "(rate(node_network_receive_bytes_total{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\", device=\"eth0\"}[$__rate_interval]) * 8) * -1",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Network IO - C",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.198:9100\", device=\"eth0\"}[$__rate_interval]) * 8",
     "legendFormat": "Out"
    },
    {
     "expr": "(rate(node_network_receive_bytes_total{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.198:9100\", device=\"eth0\"}[$__rate_interval]) * 8) * -1",
     "legendFormat": "In"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Disk I/O - A",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.193:9100\", device=\"vda\"}[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "(rate(node_disk_written_bytes_total{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.193:9100\", device=\"vda\"}[$__rate_interval])) * -1",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Disk I/O - B",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\", device=\"vda\"}[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "(rate(node_disk_written_bytes_total{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.191:9100\", device=\"vda\"}[$__rate_interval])) * -1",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.198:9100\", device=\"vda\"}[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "(rate(node_disk_written_bytes_total{job=\"crm-prod-opensearch-nodes\", instance=\"209.38.251.198:9100\", device=\"vda\"}[$__rate_interval])) * -1",
     "legendFormat": "write"
    }
   ]
  }
 ]
}