{
 "title": "Platform Availability",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "env",
    "query": {
     "query": "label_values(kube_pod_info{project=\"crm\"}, env)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{project=\"crm\",env=\"$env\"}, namespace)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(kube_pod_container_info{project=\"crm\", env=\"$env\", namespace=\"$namespace\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Detailed HTTP stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests[1m]",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (application, uri) (rate(http_server_requests_seconds_count{env=\"$env\", uri!~\".*actuator.*\", uri!~\".*prometheus*\", uri!~\"/health.*\", uri!=\"/**\", uri!~\"/info\", uri!~\"root\", uri!~\"/public/socket.*\"})[1m])",
     "legendFormat": "{{application}} {{uri}}"
    }
   ]
  },
  { "title": "General Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Connection Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(sum by (application) (hikaricp_connections_timeout_total{env=\"$env\"})[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Service 1m",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (application) (rate(http_server_requests_seconds_count{env=\"$env\", uri!~\".*actuator.*\", uri!~\".*prometheus*\", uri!~\"/health\", uri!~\"/info\", uri!~\"root\"})[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Availability",
   "type": "timeseries",
   "description": "Based on number healthy replicas from deployment group",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(kube_deployment_status_replicas_available{namespace=\"$namespace\", env=\"$env\"} / kube_deployment_spec_replicas{namespace=\"$namespace\", env=\"$env\"})\n",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{env=\"$env\", namespace=\"$namespace\", container=~\"$application\"}[1h])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Topic Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum by(service, topic) (kafka_consumer_fetch_manager_records_lag{env=\"$env\", application=~\"$application\", topic!=\"wet_tick_events\", topic!=\"liqudity_provider_tick_events\"})",
     "legendFormat": "{{service}} -> {{topic}} "
    }
   ]
  },
  {
   "title": "Kafka Topic Fetch Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (topic, service)(kafka_consumer_fetch_manager_fetch_size_avg{env=\"$env\", application=~\"$application\"})",
     "legendFormat": "{{service}} -> {{topic}}"
    }
   ]
  },
  {
   "title": "Last Error per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{env=\"$env\", namespace=\"$namespace\", container=~\"$application\"}",
     "legendFormat": "{{container}} [{{reason}}]"
    }
   ]
  }
 ]
}