{
 "title": "PostgreSQL Nodes",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"crm-prod-pgsql\"}, instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "PGSQL MAIN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"crm-prod-pgsql\",instance=\"104.248.194.173:9100\", mode=\"idle\"}[1m]) * 100))\n",
     "legendFormat": "cpu avg"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"crm-prod-pgsql\", instance=\"104.248.194.173:9100\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{job=\"crm-prod-pgsql\", instance=\"104.248.194.173:9100\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{job=\"crm-prod-pgsql\", instance=\"104.248.194.173:9100\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"crm-prod-pgsql\", instance=\"104.248.194.173:9100\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"crm-prod-pgsql\", instance=\"104.248.194.173:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"crm-prod-pgsql\", instance=\"104.248.194.173:9100\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node_filesystem_size_bytes{job=\"crm-prod-pgsql\", instance=\"104.248.194.173:9100\", fstype!=\"\", mountpoint=\"/\"})\n"
    },
    {
     "expr": "max by (mountpoint) (node_filesystem_avail_bytes{job=\"crm-prod-pgsql\", instance=\"104.248.194.173:9100\", fstype!=\"\", mountpoint=\"/\"})\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"crm-prod-pgsql\",instance=\"104.248.194.173:9100\", mode=\"idle\"}[1m]) * 100))",
     "legendFormat": "cpu usage avg"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"crm-prod-pgsql\", instance=\"104.248.194.173:9100\"}\n-\n  node_memory_MemFree_bytes{job=\"crm-prod-pgsql\", instance=\"104.248.194.173:9100\"}\n-\n  node_memory_Buffers_bytes{job=\"crm-prod-pgsql\", instance=\"104.248.194.173:9100\"}\n-\n  node_memory_Cached_bytes{job=\"crm-prod-pgsql\", instance=\"104.248.194.173:9100\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"crm-prod-pgsql\", instance=\"104.248.194.173:9100\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"crm-prod-pgsql\", instance=\"104.248.194.173:9100\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"crm-prod-pgsql\", instance=\"104.248.194.173:9100\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"crm-prod-pgsql\", instance=\"104.248.194.173:9100\", device=\"eth0\"}[$__rate_interval]) * 8",
     "legendFormat": "Out"
    },
    {
     "expr": "(rate(node_network_receive_bytes_total{job=\"crm-prod-pgsql\", instance=\"104.248.194.173:9100\", device=\"eth0\"}[$__rate_interval]) * 8) * -1",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"crm-prod-pgsql\", instance=\"104.248.194.173:9100\", device=\"vda\"}[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "(rate(node_disk_written_bytes_total{job=\"crm-prod-pgsql\", instance=\"104.248.194.173:9100\", device=\"vda\"}[$__rate_interval])) * -1",
     "legendFormat": "write"
    }
   ]
  },
  { "title": "PGSQL ARCHSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"crm-prod-pgsql\",instance=\"161.35.219.246:9100\", mode=\"idle\"}[1m]) * 100))\n",
     "legendFormat": "cpu avg"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"crm-prod-pgsql\", instance=\"161.35.219.246:9100\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{job=\"crm-prod-pgsql\", instance=\"161.35.219.246:9100\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{job=\"crm-prod-pgsql\", instance=\"161.35.219.246:9100\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"crm-prod-pgsql\", instance=\"161.35.219.246:9100\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"crm-prod-pgsql\", instance=\"161.35.219.246:9100\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"crm-prod-pgsql\", instance=\"161.35.219.246:9100\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node_filesystem_size_bytes{job=\"crm-prod-pgsql\", instance=\"161.35.219.246:9100\", fstype!=\"\", mountpoint=\"/\"})\n"
    },
    {
     "expr": "max by (mountpoint) (node_filesystem_avail_bytes{job=\"crm-prod-pgsql\", instance=\"161.35.219.246:9100\", fstype!=\"\", mountpoint=\"/\"})\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"crm-prod-pgsql\",instance=\"161.35.219.246:9100\", mode=\"idle\"}[1m]) * 100))",
     "legendFormat": "cpu usage avg"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"crm-prod-pgsql\", instance=\"161.35.219.246:9100\"}\n-\n  node_memory_MemFree_bytes{job=\"crm-prod-pgsql\", instance=\"161.35.219.246:9100\"}\n-\n  node_memory_Buffers_bytes{job=\"crm-prod-pgsql\", instance=\"161.35.219.246:9100\"}\n-\n  node_memory_Cached_bytes{job=\"crm-prod-pgsql\", instance=\"161.35.219.246:9100\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"crm-prod-pgsql\", instance=\"161.35.219.246:9100\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"crm-prod-pgsql\", instance=\"161.35.219.246:9100\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"crm-prod-pgsql\", instance=\"161.35.219.246:9100\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"crm-prod-pgsql\", instance=\"161.35.219.246:9100\", device=\"eth0\"}[$__rate_interval]) * 8",
     "legendFormat": "Out"
    },
    {
     "expr": "(rate(node_network_receive_bytes_total{job=\"crm-prod-pgsql\", instance=\"161.35.219.246:9100\", device=\"eth0\"}[$__rate_interval]) * 8) * -1",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"crm-prod-pgsql\", instance=\"161.35.219.246:9100\", device=\"vda\"}[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "(rate(node_disk_written_bytes_total{job=\"crm-prod-pgsql\", instance=\"161.35.219.246:9100\", device=\"vda\"}[$__rate_interval])) * -1",
     "legendFormat": "write"
    }
   ]
  }
 ]
}