{
 "title": "PostgreSQL Detailed",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "pgsql",
  "crm",
  "prod"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   { "name": "project", "label": "project", "query": { "query": "label_values(project)" } },
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values({project=\"$project\"},env)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(pg_up{job=\"crm-prod-pgsql\"})"
    }
   },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "mode",
    "label": "Lock table",
    "query": {
     "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"},mode)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime Postgres",
   "type": "stat",
   "description": "Time from last Postgres process restart.  < 5m Error, < 30m Warn thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_postmaster_start_time_seconds{job=\"crm-prod-pgsql\", instance=\"$instance\"} * 1000"
    }
   ]
  },
  {
   "title": "rollback/commit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(pg_stat_database_xact_rollback{job=\"crm-prod-pgsql\", instance=\"$instance\"})/sum(pg_stat_database_xact_commit{job=\"crm-prod-pgsql\", instance=\"$instance\"}))*100"
    }
   ]
  },
  {
   "title": "Count idle in transaction",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{job=\"crm-prod-pgsql\", instance=\"$instance\",state=\"idle in transaction\"})",
     "legendFormat": "idle in transaction sessions"
    }
   ]
  },
  {
   "title": "Sum ExclusiveLock on instance",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(pg_locks_count{datname=~\"$datname\", datname!=\"postgres\", instance=~\"$instance\", mode=~\"$mode\", mode!=\"accesssharelock\", mode!=\"rowsharelock\", mode!=\"sharelock\"} > 1)",
     "legendFormat": "{{datname}} {{mode}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "PG buffer cache hit rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(100*sum(pg_stat_database_blks_hit{job=\"crm-prod-pgsql\", instance=\"$instance\"}) / (sum(pg_stat_database_blks_hit{job=\"crm-prod-pgsql\", instance=\"$instance\"}) + sum(pg_stat_database_blks_read{job=\"crm-prod-pgsql\", instance=\"$instance\"})),0.1)",
     "legendFormat": "pg cache hit rate"
    }
   ]
  },
  {
   "title": "% current/total connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(pg_stat_activity_count{job=\"crm-prod-pgsql\", instance=\"$instance\"}) / sum(pg_settings_max_connections)) * 100",
     "legendFormat": "total/all connection"
    }
   ]
  },
  {
   "title": "Transactions per second",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(pg_stat_database_xact_rollback{job=\"crm-prod-pgsql\", instance=\"$instance\"}[1m])) + sum(rate(pg_stat_database_xact_commit{job=\"crm-prod-pgsql\", instance=\"$instance\"}[1m])))/60",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Sum ShareLock on instance",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(pg_locks_count{datname=~\"$datname\", datname!=\"postgres\", instance=~\"$instance\", mode=~\"$mode\", mode!=\"accessexclusivelock\", mode!=\"exclusivelock\", mode!=\"rowexclusivelock\", mode!=\"sharerowexclusivelock\", mode!=\"shareupdateexclusivelock\" })",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Queries per second",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_calls{instance=~\"$instance\"}[1m]))/60"
    }
   ]
  },
  {
   "title": "Mean query time avg 1m by instance",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_mean_time_seconds{datname!~\"template.*\", datname!~\"postgres\", instance=~\"$instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "stat",
   "description": "Connected sessions, including Postgres internal processes like Autovacuum. < 1 Warn / > 300 Error thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\"})"
    }
   ]
  },
  {
   "title": "TOP-5 Most long-running queries by mean_time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TOP-5 Most long-running queries by mean_time second",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(5, pg_stat_statements_mean_time_seconds{datname!~\"template.*\", datname!~\"postgres\", instance=~\"$instance\", datname=~\"$datname\"})"
    }
   ]
  },
  {
   "title": "TOP-5 Most called queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TOP-5 Most called queries",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(5, pg_stat_statements_calls{datname!~\"template.*\", datname!~\"postgres\", instance=~\"$instance\", datname=~\"$datname\"})"
    }
   ]
  },
  {
   "title": "Syntetic query time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mean query time avg 1m by instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_mean_time_seconds{datname!~\"template.*\", datname!~\"postgres\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Mean query time by entire database",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pg_stat_statements_calls{datname!~\"template.*\", datname!~\"postgres\", instance=~\"$instance\", datname=~\"$datname\"}[1m])) by (datname) > 100",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Syntetic queries count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total queries count (1m rate) by entire instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pg_stat_statements_calls{datname!~\"template.*\", datname!~\"postgres\", instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total queries count (1m rate) by database",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pg_stat_statements_calls{datname!~\"template.*\", datname!~\"postgres\", instance=~\"$instance\", datname=~\"$datname\"}[1m])) by (datname) > 100",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Buffers & Blocks Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Operations with Blocks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_blk_read_time{datname=~\"$datname\",instance=~\"$instance\",datname!~\"template.*|postgres\"}[5m])",
     "legendFormat": "Read {{datname}}"
    },
    {
     "expr": "rate(pg_stat_database_blk_write_time{datname=~\"$datname\",instance=~\"$instance\",datname!~\"template.*|postgres\"}[5m])",
     "legendFormat": "Write {{datname}}"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_alloc{job=\"crm-prod-pgsql\", instance=\"$instance\"}[$interval]) or \nirate(pg_stat_bgwriter_buffers_alloc{job=\"crm-prod-pgsql\", instance=\"$instance\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Allocated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_backend_fsync{job=\"crm-prod-pgsql\", instance=\"$instance\"}[$interval]) or\nirate(pg_stat_bgwriter_buffers_backend_fsync{job=\"crm-prod-pgsql\", instance=\"$instance\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Fsync calls by a backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_backend{job=\"crm-prod-pgsql\", instance=\"$instance\"}[$interval]) or\nirate(pg_stat_bgwriter_buffers_backend{job=\"crm-prod-pgsql\", instance=\"$instance\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written directly by a backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_clean{job=\"crm-prod-pgsql\", instance=\"$instance\"}[$interval]) or \nirate(pg_stat_bgwriter_buffers_clean{job=\"crm-prod-pgsql\", instance=\"$instance\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written by the background writer",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_checkpoint{job=\"crm-prod-pgsql\", instance=\"$instance\"}[5m]) or\nirate(pg_stat_bgwriter_buffers_checkpoint{job=\"crm-prod-pgsql\", instance=\"$instance\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written during checkpoints",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Connection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Count general connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pg_settings_max_connections", "legendFormat": "max_connections" },
    {
     "expr": "sum(pg_stat_activity_count{job=\"crm-prod-pgsql\", instance=\"$instance\"})",
     "legendFormat": "total connections"
    },
    {
     "expr": "sum(pg_stat_activity_count{job=\"crm-prod-pgsql\", instance=\"$instance\",state=\"idle\"})",
     "legendFormat": "idle sessions"
    },
    {
     "expr": "sum(pg_stat_activity_count{job=\"crm-prod-pgsql\", instance=\"$instance\",state=\"active\"})",
     "legendFormat": "active sessions"
    },
    {
     "expr": "sum(pg_stat_activity_count{job=\"crm-prod-pgsql\", instance=\"$instance\",state=\"idle in transaction\"})",
     "legendFormat": "idle in transaction sessions"
    },
    {
     "expr": "sum(pg_stat_activity_count{job=\"crm-prod-pgsql\", instance=\"$instance\",state=\"idle in transaction (aborted)\"})",
     "legendFormat": "idle in transaction (aborted) sessions"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state=\"active\"} !=0",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Connections in detail",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, (pg_stat_activity_count{job=\"crm-prod-pgsql\", instance=\"$instance\"}))",
     "legendFormat": "{{datname}} {{state}}"
    }
   ]
  },
  {
   "title": "General Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current fetch data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{job=\"crm-prod-pgsql\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{job=\"crm-prod-pgsql\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{job=\"crm-prod-pgsql\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{job=\"crm-prod-pgsql\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Seq Page Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_seq_page_cost{job=\"crm-prod-pgsql\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Disk-Page Buffers",
   "type": "stat",
   "description": "The setting wal_buffers defines how much memory is used for caching the write-ahead log entries. Generally this value is small (3% of shared_buffers value), but it may need to be modified for heavily loaded servers.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_wal_buffers_bytes{job=\"crm-prod-pgsql\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{job=\"crm-prod-pgsql\", datname=~\"$datname\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{job=\"crm-prod-pgsql\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_random_page_cost{job=\"crm-prod-pgsql\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{job=\"crm-prod-pgsql\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{job=\"crm-prod-pgsql\", instance=\"$instance\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{job=\"crm-prod-pgsql\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Transactions commits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{job=\"crm-prod-pgsql\", instance=\"$instance\"}[1m]) > 1",
     "legendFormat": "{{datname}} commits"
    }
   ]
  },
  {
   "title": "Transactions rollbacks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{job=\"crm-prod-pgsql\", instance=\"$instance\"}[1m]) > 1",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Longest Transaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Longest Transaction",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration{job=\"crm-prod-pgsql\", instance=\"$instance\"} > 0",
     "legendFormat": "{{datname}} max_tx_duration [{{state}}]"
    }
   ]
  },
  {
   "title": "Select, insert, update",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Read Stats",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{job=\"crm-prod-pgsql\", instance=\"$instance\"}[5m]) > 1000",
     "legendFormat": "{{datname}} SELECT (index scan)"
    },
    {
     "expr": "rate(pg_stat_database_tup_returned{job=\"crm-prod-pgsql\", instance=\"$instance\"}[5m]) > 1000",
     "legendFormat": "{{datname}} SELECT (table scan)"
    }
   ]
  },
  {
   "title": "Change Stats",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{job=\"crm-prod-pgsql\", instance=\"$instance\"}[5m]) > 1",
     "legendFormat": "{{datname}} INSERT"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{job=\"crm-prod-pgsql\", instance=\"$instance\"}[5m]) > 1",
     "legendFormat": "{{datname}} UPDATE"
    },
    {
     "expr": "rate(pg_stat_database_tup_deleted{job=\"crm-prod-pgsql\", instance=\"$instance\"}[5m]) > 1",
     "legendFormat": "{{datname}} DELETE"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Replication Lag (Only for Replica)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(pg_replication_lag{job=\"crm-prod-pgsql\", instance=\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Conflicts & Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Lock Tables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "pg_locks_count{datname=~\"$datname\", datname!=\"postgres\", instance=~\"$instance\", mode=~\"$mode\"} > 1",
     "legendFormat": "{{datname}} {{mode}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Canceled Queries",
   "type": "graph",
   "description": "Based on pg_stat_database_conflicts view",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_bufferpin{instance=~\"$instance\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_bufferpin{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Pinned buffers"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_deadlock{instance=~\"$instance\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_deadlock{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Deadlocks"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_lock{instance=~\"$instance\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_lock{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Lock timeouts"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_snapshot{instance=~\"$instance\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_snapshot{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Old snapshots"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_tablespace{instance=~\"$instance\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_tablespace{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Dropped tablespaces "
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_conflicts{job=\"crm-prod-pgsql\", instance=\"$instance\"}[5m])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "rate(pg_stat_database_deadlocks{job=\"crm-prod-pgsql\", instance=\"$instance\"}[5m])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Repl. Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "conflicts",
     "expr": "sum(rate(pg_stat_database_deadlocks{job=\"crm-prod-pgsql\", instance=\"$instance\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "deadlocks",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "deadlocks",
     "expr": "sum(rate(pg_stat_database_conflicts{job=\"crm-prod-pgsql\", instance=\"$instance\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "conflicts",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "deadlocks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache & Temp file",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PG buffer cache hit rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "round(100*sum(pg_stat_database_blks_hit{job=\"crm-prod-pgsql\", instance=\"$instance\"}) / (sum(pg_stat_database_blks_hit{job=\"crm-prod-pgsql\", instance=\"$instance\"}) + sum(pg_stat_database_blks_read{job=\"crm-prod-pgsql\", instance=\"$instance\"})),0.1)",
     "legendFormat": "pg cache hit rate"
    }
   ]
  },
  {
   "title": "Temp File",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 125 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{job=\"crm-prod-pgsql\", instance=\"$instance\"}[5m])",
     "legendFormat": "{{datname}} Temp Bytes"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{job=\"crm-prod-pgsql\", instance=\"$instance\"} / (pg_stat_database_blks_read{job=\"crm-prod-pgsql\", instance=\"$instance\"} + pg_stat_database_blks_hit{job=\"crm-prod-pgsql\", instance=\"$instance\"})",
     "legendFormat": "{{datname}} Cache Hit Rate"
    }
   ]
  }
 ]
}