{
 "title": "Spring Statistics",
 "description": "Dashboard for Spring Boot2.1 Statistics(based on Spring Boot2 Statistic by micrometer-prometheus).",
 "tags": [
  "spring ",
  "java",
  "micrometer"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(system_cpu_count,project)"
    }
   },
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(system_cpu_count{project=\"$project\"},env)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{project=\"$project\", env=\"$env\"},namespace)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{project=\"$project\", env=\"$env\", namespace=\"$namespace\"},application)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{project=\"$project\", env=\"$env\", application=\"$application\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "repeat": "memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{project=\"$project\",env=\"$env\", application=\"$application\", instance=~\"$instance\"}",
     "legendFormat": "Used {{pod}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{project=\"$project\",env=\"$env\", application=\"$application\", instance=~\"$instance\"}",
     "legendFormat": "Commited {{pod}}"
    },
    {
     "expr": "jvm_memory_max_bytes{project=\"$project\",env=\"$env\", application=\"$application\", instance=~\"$instance\"}",
     "legendFormat": "Max {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{project=\"$project\",env=\"$env\", application=\"$application\", instance=~\"$instance\"}[5m])",
     "legendFormat": "allocated  {{pod}}"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{project=\"$project\",env=\"$env\", application=\"$application\", instance=~\"$instance\"}[5m])",
     "legendFormat": "promoted {{pod}}"
    }
   ]
  },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "repeat": "memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{project=\"$project\",env=\"$env\", application=\"$application\", instance=~\"$instance\"}",
     "legendFormat": "Used {{pod}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{project=\"$project\",env=\"$env\", application=\"$application\", instance=~\"$instance\"}",
     "legendFormat": "Commited {{pod}}"
    },
    {
     "expr": "jvm_memory_max_bytes{project=\"$project\",env=\"$env\", application=\"$application\", instance=~\"$instance\"}",
     "legendFormat": "Max {{pod}}"
    }
   ]
  },
  {
   "title": "Requests Per Pod Deviation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(pod)(irate( http_server_requests_seconds_count{uri!~\".*actuator.*\", uri!~\".*prometheus*\", uri!~\"/health\", uri!~\"/info\", uri!~\"root\", project=\"$project\",env=\"$env\", application=\"$application\"}[15s] ))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", project=\"$project\",env=\"$env\", instance=~\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\", project=\"$project\",env=\"$env\",instance=~\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\", instance=~\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\",instance=~\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 17 },
   "targets": [
    {
     "expr": "system_load_average_1m{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}  Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}} CPU Core Size"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}} Daemon"
    },
    {
     "expr": "jvm_threads_live_threads{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}  Live"
    },
    {
     "expr": "jvm_threads_peak_threads{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}  Peak"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "system_cpu_usage{project=\"$project\",env=\"$env\", application=\"$application\", instance=~\"$instance\"}",
     "legendFormat": "{{pod}} System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}  Process CPU Usage"
    }
   ]
  },
  {
   "title": "Jetty Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "jetty_threads_idle{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}  Idle"
    },
    {
     "expr": "jetty_threads_jobs{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}  Thread Jobs"
    },
    {
     "expr": "jetty_threads_current{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}  Current thread"
    },
    {
     "expr": "jetty_threads_busy{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}} Threads Busy"
    }
   ]
  },
  {
   "title": "Max Threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jetty_threads_config_max{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}  "
    }
   ]
  },
  {
   "title": "Busy threads",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jetty_threads_idle{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}  Idle"
    },
    {
     "expr": "jetty_threads_busy{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}} Threads Busy"
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\", exception=\"None\", uri!~\".*actuator.*\", uri!~\".*prometheus*\", uri!~\"/health\", uri!~\"/info\", uri!~\"root\"}[15s]) / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\", exception=\"None\", uri!~\".*actuator.*\", uri!~\".*prometheus*\", uri!~\"/health\", uri!~\"/info\", uri!~\"root\"}[15s])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\", exception=\"None\", uri!~\".*actuator.*\", uri!~\".*prometheus*\", uri!~\"/health\", uri!~\"/info\", uri!~\"root\"}[15s]) / rate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\", exception=\"None\", uri!~\".*actuator.*\", uri!~\".*prometheus*\", uri!~\"/health\", uri!~\"/info\", uri!~\"root\"}[15s])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\", uri!~\".*actuator.*\", uri!~\".*prometheus*\", uri!~\"/health\", uri!~\"/info\", uri!~\"root\"}[15s])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}  {{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "GC Stop the World Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{pod}} {{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "HikariCP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\"}",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 77 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}} Active"
    },
    {
     "expr": "hikaricp_connections_idle{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}} Idle"
    },
    {
     "expr": "hikaricp_connections_pending{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}} Pending"
    }
   ]
  },
  {
   "title": "Connection Timeout Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connection Creation Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "hikaricp_connections_creation_seconds_sum{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"} / hikaricp_connections_creation_seconds_count{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}} Creation Time"
    }
   ]
  },
  {
   "title": "Connection Usage Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 85 },
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"} / hikaricp_connections_usage_seconds_count{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}} Usage Time"
    }
   ]
  },
  {
   "title": "Connection Acquire Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 85 },
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_sum{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"} / hikaricp_connections_acquire_seconds_count{instance=~\"$instance\", application=\"$application\", project=\"$project\", env=\"$env\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}  Acquire Time"
    }
   ]
  }
 ]
}