{
 "title": "DevOpsProdigy KubeGraf Daemonset's Dashboard",
 "tags": [
  "kubernetes",
  "DevOpsProdigy",
  "daemonset",
  "KubeGraf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "project",
    "query": {
     "query": "label_values(kubernetes_build_info,project)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info{project=\"$project\"}, env)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{env=\"$cluster\", project=\"$project\"},namespace)"
    }
   },
   {
    "name": "daemonset",
    "query": {
     "query": "label_values(kube_daemonset_labels{env=\"$cluster\",namespace=\"$namespace\"}, daemonset)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "query_result(avg_over_time(kube_pod_info{namespace=\"$namespace\",pod=~\"$daemonset-.*\"}[$__range]))"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "query_result(avg_over_time(kube_pod_container_info{env=\"$cluster\",namespace=\"$namespace\",pod=~\"$daemonset-.*\",container!=\"\",container!=\"POD\"}[$__range]))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Application Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Daemonsets status",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{env=\"$cluster\", namespace=\"$namespace\", daemonset=\"$daemonset\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "kube_daemonset_status_number_unavailable{env=\"$cluster\", namespace=\"$namespace\", daemonset=\"$daemonset\"}",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Daemonsets status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{env=\"$cluster\", namespace=\"$namespace\", daemonset=\"$daemonset\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "kube_daemonset_status_number_unavailable{env=\"$cluster\", namespace=\"$namespace\", daemonset=\"$daemonset\"}",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Containers' statuses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{env=\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Ready [$daemonset / {{pod}} / {{container}}]"
    },
    {
     "expr": "kube_pod_container_status_running{env=\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Running [$daemonset / {{pod}} / {{container}}]"
    },
    {
     "expr": "kube_pod_container_status_running{env=\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Running [$daemonset / {{pod}} / {{container}}]"
    },
    {
     "expr": "kube_pod_container_status_waiting{env=\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Waiting [$daemonset / {{pod}} / {{container}}]"
    },
    {
     "expr": "kube_pod_container_status_terminated{env=\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Terminated [$daemonset / {{pod}} / {{container}}]"
    }
   ]
  },
  {
   "title": "Containers' restarts total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{env=\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers' restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{env=\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Restarts [$daemonset / {{pod}} / {{ container}} ]"
    }
   ]
  },
  {
   "title": "Application's Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!=\"POD\", container=~\"$container\"}) by (pod, container) or sum(label_replace(label_replace(container_memory_working_set_bytes{namespace=\"$namespace\", pod_name=~\"$pod\", container_name!=\"\", container_name!=\"POD\", container_name=~\"$container\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\"), \"container\", \"$1\", \"container_name\", \"(.*)\")) by (pod, container)",
     "legendFormat": "Used: {{pod}} / {{container}}"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by (pod, container)",
     "legendFormat": "Requested: {{pod}} / {{container}}"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by (pod, container)",
     "legendFormat": "Limited: {{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[2m])) by (pod, container) or sum(label_replace(label_replace(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}[2m]),\"pod\",\"$1\",\"pod_name\",\"(.*)\"),\"container\",\"$1\",\"container_name\",\"(.*)\")) by (pod, container)",
     "legendFormat": "Used: {{pod}} / {{container}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Requested: {{pod}} / {{container}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Limited: {{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "Traffic transmit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$pod\"}[2m]) or\nlabel_replace(irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod_name=~\"$pod\"}[2m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\")",
     "legendFormat": "{{interface}} : [{{pod}}]"
    }
   ]
  },
  {
   "title": "Traffic receive",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$pod\"}[2m]) or label_replace(irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod_name=~\"$pod\"}[2m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\")",
     "legendFormat": "{{interface}} : [{{pod}}]"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_reads_total{namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!=\"POD\"}[5m]) or label_replace(label_replace(rate(container_fs_reads_total{namespace=\"$namespace\", pod_name=~\"$pod\", container_name!=\"\", container_name!=\"POD\"}[5m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\"), \"container\", \"$1\", \"container_name\", \"(.*)\")",
     "legendFormat": "Reads {{ device }} [{{ pod }} / {{ container }}]"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_writes_total{namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!=\"POD\"}[5m]) or label_replace(label_replace(rate(container_fs_writes_total{namespace=\"$namespace\", pod_name=~\"$pod\", container_name!=\"\", container_name!=\"POD\"}[5m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\"), \"container\", \"$1\", \"container_name\", \"(.*)\")",
     "legendFormat": "Writes {{ device }} [{{ pod }} / {{ container }}]"
    }
   ]
  }
 ]
}