{
 "title": "Kubernetes / Views / Global",
 "description": "This is a modern 'Global View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(kube_pod_info, project)"
    }
   },
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(kube_pod_info{project=\"$project\"}, env)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global CPU  Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{project=\"$project\", env=\"$env\", mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{project=\"$project\", env=\"$env\", unit=\"core\"}) / sum(machine_cpu_cores{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{project=\"$project\", env=\"$env\", unit=\"core\"}) / sum(machine_cpu_cores{project=\"$project\", env=\"$env\" })",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Global RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{project=\"$project\", env=\"$env\"} - node_memory_MemAvailable_bytes{project=\"$project\", env=\"$env\"}) / sum(node_memory_MemTotal_bytes{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{project=\"$project\", env=\"$env\", unit=\"byte\"}) / sum(machine_memory_bytes{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{project=\"$project\", env=\"$env\", unit=\"byte\"}) / sum(machine_memory_bytes{project=\"$project\", env=\"$env\" })",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{project=\"$project\", env=\"$env\", job=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Kubernetes Resource Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_namespace_labels{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Namespaces"
    },
    {
     "expr": "sum(kube_pod_container_status_running{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase='Running', project=\"$project\", env=\"$env\" })",
     "legendFormat": "Running Pods"
    },
    {
     "expr": "sum(kube_service_info{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "sum(kube_endpoint_info{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Endpoints"
    },
    {
     "expr": "sum(kube_ingress_info{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Ingresses"
    },
    {
     "expr": "sum(kube_deployment_labels{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(kube_statefulset_labels{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(kube_daemonset_labels{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Daemonsets"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_info{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Persistent Volume Claims"
    },
    {
     "expr": "sum(kube_hpa_labels{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Horizontal Pod Autoscalers"
    },
    {
     "expr": "sum(kube_configmap_info{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Configmaps"
    },
    {
     "expr": "sum(kube_secret_info{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Secrets"
    },
    {
     "expr": "sum(kube_networkpolicy_labels{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Network Policies"
    },
    {
     "expr": "count(up{project=\"$project\", env=\"$env\", job=\"node-exporter\"})",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_created{project=\"$project\", env=\"$env\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(1-rate(node_cpu_seconds_total{project=\"$project\", env=\"$env\", mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{project=\"$project\", env=\"$env\", unit=\"core\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{project=\"$project\", env=\"$env\", unit=\"core\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_cpu_cores{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{project=\"$project\", env=\"$env\"} - node_memory_MemAvailable_bytes{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{project=\"$project\", env=\"$env\", unit=\"byte\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{project=\"$project\", env=\"$env\", unit=\"byte\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_memory_bytes{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{project=\"$project\", env=\"$env\", phase='Running'})"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{project=\"$project\", env=\"$env\", mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "CPU usage in %"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{project=\"$project\", env=\"$env\"} - node_memory_MemAvailable_bytes{project=\"$project\", env=\"$env\" }) / sum(node_memory_MemTotal_bytes{project=\"$project\", env=\"$env\"})",
     "legendFormat": "Memory usage in %"
    }
   ]
  },
  {
   "title": "CPU Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{project=\"$project\", env=\"$env\", image!=\"\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{project=\"$project\", env=\"$env\", image!=\"\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Utilization by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{project=\"$project\", env=\"$env\", mode=\"idle\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{project=\"$project\", env=\"$env\"} - node_memory_MemAvailable_bytes{project=\"$project\", env=\"$env\"}) by (instance)",
     "legendFormat": "{{ node}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Global Network Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{project=\"$project\", env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "Total received bytes"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{project=\"$project\", env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "Total transmitted bytes"
    }
   ]
  },
  {
   "title": "Network Saturation - Packets dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{project=\"$project\", env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "Packets dropped (receive)"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_dropped_total{project=\"$project\", env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "Packets dropped (transmit)"
    }
   ]
  },
  {
   "title": "Network Received by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{project=\"$project\", env=\"$env\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "Received bytes in {{ namespace }}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{project=\"$project\", env=\"$env\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "Transmitted bytes in {{ namespace }}"
    }
   ]
  },
  {
   "title": "Network Received by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{project=\"$project\", env=\"$env\"}[$__rate_interval])) by (node)",
     "legendFormat": "Received bytes in {{ node }}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{project=\"$project\", env=\"$env\"}[$__rate_interval])) by (node)",
     "legendFormat": "Transmitted bytes in {{ node }}"
    }
   ]
  }
 ]
}