{
 "title": "Kubernetes / Networking / Cluster",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(kube_pod_info, project)"
    }
   },
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(kube_pod_info{project=\"$project\"}, env)"
    }
   },
   { "name": "interval", "query": "4h" },
   { "name": "resolution", "query": "30s,5m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Current Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Rate of Bytes Received",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_receive_bytes_total{project=\"$project\", env=\"$env\", namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Current Rate of Bytes Transmitted",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_bytes_total{project=\"$project\", env=\"$env\", namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Current Status",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_receive_bytes_total{project=\"$project\", env=\"$env\", namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_bytes_total{project=\"$project\", env=\"$env\", namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
    },
    {
     "expr": "sort_desc(avg(irate(container_network_receive_bytes_total{project=\"$project\", env=\"$env\", namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
    },
    {
     "expr": "sort_desc(avg(irate(container_network_transmit_bytes_total{project=\"$project\", env=\"$env\", namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_receive_packets_total{project=\"$project\", env=\"$env\", namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_packets_total{project=\"$project\", env=\"$env\", namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_receive_packets_dropped_total{project=\"$project\", env=\"$env\", namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_packets_dropped_total{project=\"$project\", env=\"$env\", namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
    }
   ]
  },
  {
   "title": "Average Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Average Rate of Bytes Received",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sort_desc(avg(irate(container_network_receive_bytes_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Average Rate of Bytes Transmitted",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sort_desc(avg(irate(container_network_transmit_bytes_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_receive_bytes_total{project=\"$project\", env=\"$env\", namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_bytes_total{project=\"$project\", env=\"$env\", namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Received Packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_receive_packets_total{project=\"$project\", env=\"$env\", namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_packets_total{project=\"$project\", env=\"$env\", namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate of Received Packets Dropped",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(irate(container_network_receive_packets_dropped_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets Dropped",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(irate(container_network_transmit_packets_dropped_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  }
 ]
}